# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: anmol brar
email: hey@anmolbrar.ca
about: |
  hey! welcome to my corner of the internet. i'm anmol, a 20-year-old software developer from canada and computer science student at mcgill university.

  this year i'll be...
    * a intern at [nvidia](https://nvidia.com).
    * helping [mcgill csus](https://mcgill-csus.ca) organize industry-related events.

  last year i was...
    * interning at [nvidia](https://nvidia.com) doing full stack web development and devops.
    * helping organize [mchacks](https://mchacks.ca), mcgill's largest hackathon!

  in my free time i enjoy reading books, swimming, and biking.

  if you want to get in touch, feel free to reach out via [e-mail](mailto:hey@anmolbrar.ca) or a direct message through [twitter](https://www.twitter.com/brarsanmol).
description: >- # this means to ignore newlines until "baseurl:"
  Anmol Brar is a 20 year old software developer from Canada currently studying Computer Science at McGill University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
resume: assets/Anmol_Brar_Resume.pdf
google_analytics_tracking_id: G-KVQ4VTVEYK

contacts:
  rss: "/feed.xml"
  mail: "mailto:hey@anmolbrar.ca"
  linkedin: "https://www.linkedin.com/in/brarsanmol"
  github: "https://www.github.com/brarsanmol"
  twitter: "https://www.twitter.com/brarsanmol"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      is_post: true

# Build settings
plugins:
  - jekyll-feed

kramdown:
  syntax_highlighter: rouge
  input: GFM
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
